// Hard Problems 数据集
// 涵盖数学、物理、化学、生物、计算机、哲学、工程、社会科学等
// 每条记录包含：基本信息 + 小朋友能懂的解释 + AI 求解 prompt 模板

export const CATEGORIES = [
  { id: 'mathematics',  name: '数学',     icon: '∑', color: 'from-blue-500 to-cyan-500',     blurb: '关于数、空间、结构的奥秘' },
  { id: 'physics',      name: '物理',     icon: '⚛', color: 'from-violet-500 to-fuchsia-500', blurb: '关于宇宙和物质如何运作' },
  { id: 'chemistry',    name: '化学',     icon: '⚗', color: 'from-emerald-500 to-teal-500',  blurb: '关于分子和物质如何变化' },
  { id: 'biology',      name: '生命科学', icon: '🧬', color: 'from-lime-500 to-green-500',   blurb: '关于生命如何运作' },
  { id: 'cs',           name: '计算机',   icon: '⌘', color: 'from-orange-500 to-rose-500',  blurb: '关于算法、智能和信息' },
  { id: 'philosophy',   name: '哲学',     icon: '?',  color: 'from-amber-500 to-yellow-500',  blurb: '关于意识、意义和价值' },
  { id: 'engineering',  name: '工程',     icon: '⚙', color: 'from-slate-500 to-zinc-500',    blurb: '把想法变成现实' },
  { id: 'social',       name: '社会',     icon: '👥', color: 'from-pink-500 to-red-500',     blurb: '关于人和社会的运作' }
];

// 挑战者勋章（基于解题数自动发放）
export const BADGES = [
  { id: 'newcomer',     name: '新手',     icon: '🌱', min_score: 0,        min_solutions: 0,  color: 'text-emerald-300' },
  { id: 'explorer',     name: '探索者',   icon: '🔍', min_score: 100,      min_solutions: 1,  color: 'text-cyan-300' },
  { id: 'thinker',      name: '思考者',   icon: '💭', min_score: 300,      min_solutions: 3,  color: 'text-violet-300' },
  { id: 'researcher',   name: '研究员',   icon: '🔬', min_score: 800,      min_solutions: 8,  color: 'text-blue-300' },
  { id: 'solver',       name: '解题者',   icon: '🧩', min_score: 2000,     min_solutions: 20, color: 'text-amber-300' },
  { id: 'pioneer',      name: '先驱',     icon: '🚀', min_score: 5000,     min_solutions: 50, color: 'text-fuchsia-300' },
  { id: 'legend',       name: '传奇',     icon: '👑', min_score: 15000,    min_solutions: 100,color: 'text-rose-300' }
];

export function getBadgesForUser(user) {
  const score = user.totalScore || 0;
  const solCount = user.solutionCount || 0;
  return BADGES.filter(b => score >= b.min_score && solCount >= b.min_solutions);
}

export const PROBLEMS = [
  // ========== 数学 ==========
  {
    id: 'millennium-riemann',
    category: 'mathematics',
    title: '黎曼猜想',
    titleEn: 'Riemann Hypothesis',
    year: 1859,
    proposer: 'Bernhard Riemann',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '素数在自然数中出现的规律，到底有没有完美的数学解释？',
    kid: '想象你有无穷多个糖果罐，每个罐子装着不同数量的糖果。素数（2、3、5、7、11...）就是那些"只能被1和自己整除"的特殊罐子。数学家们相信这些罐子有一种隐藏的排列方式。黎曼猜想就是要把这个隐藏的规律用数学公式写下来。如果写对了，能拿到100万美元！',
    formal: '黎曼 ζ 函数的所有非平凡零点都位于复平面 Re(s) = 1/2 这条直线上。',
    whyHard: '它和数论中几乎所有重要猜想纠缠在一起；过去 165 年没人能证明，也没人能举出反例。',
    aiPrompt: '你是一位友好的数学老师，向一个 12 岁的小朋友解释黎曼猜想。然后给出一份严谨的陈述、当前的研究状态、关键思路、关键参考文献。',
    tags: ['千禧年问题', '数论', '素数']
  },
  {
    id: 'millennium-pvsnp',
    category: 'mathematics',
    title: 'P vs NP',
    titleEn: 'P versus NP',
    year: 1971,
    proposer: 'Stephen Cook / Leonid Levin',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '能快速"验证"的问题，是不是也一定能"快速"解出来？',
    kid: '想象你在玩数独。如果有人给你一个数独盘面，你可以很快判断"对不对"。但要从空白开始填出一个数独答案，可能就要花很久。P vs NP 问的是：是不是所有"容易检查答案"的问题，"找答案"也容易？如果是，那整个世界很多难题都会变得超级简单（比如设计最棒的学校课表）。',
    formal: 'P = NP 是否成立？如果每个答案能在多项式时间内验证的问题也能在多项式时间内求解。',
    whyHard: '这是整个计算机科学和数学的核心问题；和密码学、优化、人工智能、组合数学都有关。',
    aiPrompt: '向一个 12 岁的小朋友解释 P vs NP 问题，用数独、找路线等例子。给出严谨陈述、研究现状、可能的思路。',
    tags: ['千禧年问题', '计算复杂性', '算法']
  },
  {
    id: 'millennium-yangmills',
    category: 'physics',
    title: '杨-米尔斯质量间隙',
    titleEn: 'Yang–Mills Existence and Mass Gap',
    year: 1954,
    proposer: 'C. N. Yang / R. Mills',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '为什么承载力的粒子（如胶子）有质量，但描述它们的方程似乎预言它们应该无质量？',
    kid: '想象一群小朋友手拉手围成一个圈传递皮球。球传递得很快（无质量）。但当他们拉得更紧时，球好像变重了。物理学家写下的方程（杨-米尔斯方程）说这些"球"应该没质量，但实验却发现它们有！这个矛盾就是"质量间隙"问题。',
    formal: '在 ℝ⁴ 上的杨-米尔斯理论中，证明存在质量间隙 Δ > 0，并给出严格的数学存在性证明。',
    whyHard: '需要把量子场论用严格的数学语言描述，目前还没有数学工具能完全做到。',
    aiPrompt: '用形象比喻解释杨-米尔斯质量间隙，给出严谨陈述、研究进展。',
    tags: ['千禧年问题', '量子场论', '规范场']
  },
  {
    id: 'millennium-navierstokes',
    category: 'mathematics',
    title: '纳维-斯托克斯方程',
    titleEn: 'Navier–Stokes Existence and Smoothness',
    year: 1822,
    proposer: 'C. L. Navier / G. Stokes',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '水为什么总是会突然变得"乱七八糟"？我们能不能预测？',
    kid: '你见过平静的河水突然变成翻滚的漩涡吗？为什么？写下来流水的方程其实很简单，但用它预测什么时候、哪里会出现湍流（混乱）——没人能做到。这是个百万美元问题。',
    formal: '证明 ℝ³ 上不可压缩纳维-斯托克斯方程的初值问题的解存在且光滑，或构造一个反例证明存在 blow-up。',
    whyHard: '湍流是物理中最难解的现象之一，涉及无穷维动力系统。',
    aiPrompt: '向小朋友解释流体湍流和纳维-斯托克斯问题，给出当前研究状态。',
    tags: ['千禧年问题', '偏微分方程', '湍流']
  },
  {
    id: 'millennium-hodge',
    category: 'mathematics',
    title: '霍奇猜想',
    titleEn: 'Hodge Conjecture',
    year: 1950,
    proposer: 'W. V. D. Hodge',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '某些抽象的几何形状，是不是都能用具体的多项式方程描述？',
    kid: '想象你在玩橡皮泥，可以用各种方式捏。但有些形状你可以用具体的"配方"做出来（比如一个面团切成1cm的方块可以拼出来），有些不行。霍奇猜想问：几何世界里所有"特殊"的形状，都能用多项式方程"配方"做出来吗？',
    formal: '对于光滑复射影簇，霍奇类都是代数闭链类的有理线性组合。',
    whyHard: '连接代数几何、拓扑和复分析，是数学中最抽象的猜想之一。',
    aiPrompt: '用简单比喻解释霍奇猜想，给出严谨陈述。',
    tags: ['千禧年问题', '代数几何', '拓扑']
  },
  {
    id: 'millennium-bsd',
    category: 'mathematics',
    title: 'BSD 猜想',
    titleEn: 'Birch and Swinnerton-Dyer Conjecture',
    year: 1960,
    proposer: 'B. Birch / P. Swinnerton-Dyer',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '椭圆曲线上有多少个有理点？是不是和某种 L 函数有关？',
    kid: '想象一个甜甜圈形状的桌面（"椭圆曲线"），你想知道上面有多少个"格点"（坐标都是分数的点）。BSD 猜想说：点数和一个特殊的数学函数（L 函数）的行为有关。如果 L(1) = 0，就有无穷多个点。',
    formal: '对于有理数域上的椭圆曲线 E，rank(E) = ord_{s=1} L(E,s)。',
    whyHard: '和数论、几何、分析都相关，Andrew Wiles 等人部分进展。',
    aiPrompt: '解释 BSD 猜想的直观意义和研究现状。',
    tags: ['千禧年问题', '数论', '椭圆曲线']
  },
  {
    id: 'twin-primes',
    category: 'mathematics',
    title: '孪生素数猜想',
    titleEn: 'Twin Prime Conjecture',
    year: 1849,
    proposer: 'de Polignac',
    difficulty: 4,
    reward: 1000,
    status: 'partially_solved',
    summary: '差为 2 的素数对（3&5, 5&7, 11&13...）是不是有无穷多？',
    kid: '素数就是只能被1和自己整除的数（2、3、5、7、11、13...）。有些素数只差2（比如3和5，5和7，11和13）。它们像双胞胎一样成对出现。孪生素数猜想说：世界上有无穷多对这样的"双胞胎素数"。',
    formal: '是否存在无穷多对素数 (p, p+2)。',
    whyHard: '2013 年张益唐证明存在无穷多对差 ≤ 7000 万的素数，但 2 仍未达到。',
    aiPrompt: '解释孪生素数猜想，包括张益唐的突破。',
    tags: ['数论', '素数', '孪生']
  },
  {
    id: 'goldbach',
    category: 'mathematics',
    title: '哥德巴赫猜想',
    titleEn: "Goldbach's Conjecture",
    year: 1742,
    proposer: 'C. Goldbach',
    difficulty: 4,
    reward: 1000,
    status: 'partially_solved',
    summary: '每个大于 2 的偶数，都能写成两个素数之和吗？',
    kid: '哥德巴赫说：4=2+2, 6=3+3, 8=3+5, 10=3+7, 12=5+7... 看起来每个偶数都能拆成两个素数相加。是真的吗？已经验证到 4 × 10¹⁸，但还是没证明。',
    formal: '每个大于 2 的偶数都可以表示为两个素数之和。',
    whyHard: '初等陈述但极难证明；陈景润证明了"1+2"（最接近的进展）。',
    aiPrompt: '解释哥德巴赫猜想，包括陈景润 1+2 的突破。',
    tags: ['数论', '加法', '偶数']
  },
  {
    id: 'collatz',
    category: 'mathematics',
    title: '考拉兹猜想 (3n+1)',
    titleEn: 'Collatz Conjecture',
    year: 1937,
    proposer: 'L. Collatz',
    difficulty: 4,
    reward: 1000,
    status: 'open',
    summary: '反复套用一个简单规则，所有正整数最终都会变成 1 吗？',
    kid: '随便挑一个正整数。偶数就除以2，奇数就乘3再加1。一直重复。猜想说：不管一开始选什么数，最后都会变成 1（然后在 4→2→1 循环）。这个简单规则让数学家们抓狂了 80 多年。',
    formal: '对于所有正整数 n，序列 a_{k+1} = a_k/2 (偶) 或 3a_k+1 (奇) 终将到达 1。',
    whyHard: '简单到小朋友都能玩，但数学家们连渐进行为都几乎完全无法证明。',
    aiPrompt: '解释考拉兹猜想，包括当前的数值验证规模和未解之处。',
    tags: ['数论', '动力系统', '初等']
  },

  // ========== 物理 ==========
  {
    id: 'quantum-gravity',
    category: 'physics',
    title: '量子引力',
    titleEn: 'Quantum Gravity',
    year: 1930,
    proposer: '—',
    difficulty: 5,
    reward: 3000,
    status: 'open',
    summary: '把广义相对论（描述大宇宙）和量子力学（描述小世界）统一起来。',
    kid: '物理学有两套说明书。一套管非常非常大的东西（星星、宇宙），叫广义相对论。一套管非常非常小的东西（原子、粒子），叫量子力学。这两套说明书在描述"黑洞中心"或"宇宙诞生瞬间"时打架。我们需要一本统一的说明书。',
    formal: '构造一个自洽的量子引力理论（候选：弦论、圈量子引力），并从中导出可观测预言。',
    whyHard: '数学上自洽、物理学上可检验、实验上可达到——三者很难同时满足。',
    aiPrompt: '用比喻解释量子引力，列举主流候选理论，评估其优劣。',
    tags: ['基础物理', '广义相对论', '量子力学']
  },
  {
    id: 'dark-matter',
    category: 'physics',
    title: '暗物质的本质',
    titleEn: 'Nature of Dark Matter',
    year: 1933,
    proposer: 'F. Zwicky',
    difficulty: 4,
    reward: 2000,
    status: 'open',
    summary: '宇宙里 85% 的物质我们看不见也摸不着，它们到底是什么？',
    kid: '天文学家们看着星系转啊转，发现按可见的物质算，转得太快了——一定还有大量"看不见的东西"在拉着星星。这些"看不见的东西"叫暗物质。但它到底是什么？粒子？黑洞？没人知道。',
    formal: '确定构成暗物质的粒子或机制，并直接探测到它。',
    whyHard: '不和电磁力作用意味着它"不可见"；候选粒子很多，但实验上一直没找到。',
    aiPrompt: '解释暗物质证据、候选粒子（WIMP、axion等）、探测实验和当前困境。',
    tags: ['宇宙学', '粒子物理', '探测']
  },
  {
    id: 'dark-energy',
    category: 'physics',
    title: '暗能量',
    titleEn: 'Dark Energy',
    year: 1998,
    proposer: 'Saul Perlmutter 等',
    difficulty: 4,
    reward: 2000,
    status: 'open',
    summary: '让宇宙加速膨胀的神秘力量，是什么？',
    kid: '宇宙就像一块面包，膨胀就是面包在变大。科学家本以为膨胀会变慢。结果发现：膨胀在变快！是什么在推？不知道。科学家给这种神秘力量起了个名字叫"暗能量"。',
    formal: '确定暗能量的物理起源（宇宙学常数？第五元素？修改引力？），并精确测量其状态方程。',
    whyHard: '是真空能量还是动态场？目前只有唯象描述。',
    aiPrompt: '解释暗能量证据、理论候选、当前观测精度。',
    tags: ['宇宙学', '加速膨胀', '真空能']
  },
  {
    id: 'turbulence',
    category: 'physics',
    title: '湍流的数学理论',
    titleEn: 'Mathematical Theory of Turbulence',
    year: 1920,
    proposer: '—',
    difficulty: 5,
    reward: 1500,
    status: 'open',
    summary: '为什么空气和水会从"丝滑"变成"混乱"？',
    kid: '你打开水龙头时，水流很平稳（层流）。开大一点，水流就乱成一片（湍流）。为什么？中间发生了什么？物理学家们吵了 100 多年，连个完整定义都给不出。',
    formal: '为三维纳维-斯托克斯方程中的湍流行为建立数学理论，包括能量级联、间歇性等。',
    whyHard: '涉及无穷多尺度的非线性相互作用；Feynman 称其为"经典物理中未解的最重要问题"。',
    aiPrompt: '用比喻解释湍流，包括 Reynolds 数、能量级联、Kolmogorov 尺度等。',
    tags: ['流体力学', '非线性', '混沌']
  },
  {
    id: 'matter-antimatter',
    category: 'physics',
    title: '物质-反物质不对称',
    titleEn: 'Baryon Asymmetry',
    year: 1967,
    proposer: 'A. Sakharov',
    difficulty: 4,
    reward: 1500,
    status: 'open',
    summary: '大爆炸应该产生等量的物质和反物质，为什么我们身边只有物质？',
    kid: '电影里你见过反物质飞船和物质飞船撞一下就全没了吧？宇宙诞生时本应物质和反物质一样多，但不知什么原因，物质多出来一点点，于是构成了我们看到的一切。这个"多出的一点点"是怎么来的？',
    formal: '解释宇宙中重子-反重子不对称（η ≈ 6 × 10⁻¹⁰），并在大统一/电弱尺度找到机制。',
    whyHard: 'CP 破缺不够；需要新的重子数破缺源和新物理。',
    aiPrompt: '解释 Sakharov 三条件、CP 破缺、超对称候选解。',
    tags: ['宇宙学', '粒子物理', 'CP 破缺']
  },
  {
    id: 'high-tc-superconductor',
    category: 'physics',
    title: '高温超导机理',
    titleEn: 'High-Tc Superconductivity',
    year: 1986,
    proposer: 'J. G. Bednorz / K. A. Müller',
    difficulty: 5,
    reward: 2000,
    status: 'open',
    summary: '为什么有些材料在相对"温暖"的温度下能无电阻导电？',
    kid: '电线通电时会发热，浪费能量。超导体可以让电通过完全没阻力，但通常需要冷到 -200°C 以下。1986年发现的新材料在"温暖"得多（-100°C）时也能超导。但物理学家们至今没完全搞懂原理。',
    formal: '为铜氧化物和铁基超导体的非常规超导相建立微观理论，并预言新的超导材料。',
    whyHard: '强关联电子系统，没有好的解析工具。',
    aiPrompt: '解释 BCS 理论、铜氧化物的反常、强关联系统的方法。',
    tags: ['凝聚态', '超导', '强关联']
  },
  {
    id: 'room-temp-superconductor',
    category: 'engineering',
    title: '室温常压超导体',
    titleEn: 'Room-Temperature Superconductor',
    year: 2020,
    proposer: '—',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '造出一种在常温下就能无阻力导电的材料。',
    kid: '如果能造出"不冷也能超导"的材料，电网就不会再浪费电，磁悬浮列车会变便宜，量子计算机会更强大。LK-99 这样的发现引发过一阵热潮，但目前仍未复现。',
    formal: '合成一种在 273 K 以上、1 atm 下表现出零电阻和完全抗磁性的材料。',
    whyHard: '需要理解和工程化强关联电子系统。',
    aiPrompt: '解释室温超导的意义、LK-99 复现情况、Hydride 系列进展。',
    tags: ['材料', '超导', '应用']
  },
  {
    id: 'proton-decay',
    category: 'physics',
    title: '质子衰变',
    titleEn: 'Proton Decay',
    year: 1974,
    proposer: 'J. C. Pati / A. Salam 等',
    difficulty: 4,
    reward: 2000,
    status: 'open',
    summary: '质子——宇宙中最稳定的粒子之一——会不会最终衰变？',
    kid: '你身体里的每个质子已经存在了 138 亿年。会不会有一天它们突然变成别的粒子？大统一理论说会，而且给出了寿命。但实验迄今没看到。',
    formal: '在实验中观测到质子衰变事件，并测出与具体 GUT 模型预言一致的寿命。',
    whyHard: '寿命预计 > 10³⁴ 年，需要巨大的探测器（超级神冈等）。',
    aiPrompt: '解释 GUT、超级神冈实验、当前质子寿命下限。',
    tags: ['粒子物理', 'GUT', '探测']
  },

  // ========== 化学 ==========
  {
    id: 'origin-of-life',
    category: 'chemistry',
    title: '生命起源的化学',
    titleEn: 'Chemical Origin of Life',
    year: 1924,
    proposer: 'A. Oparin / J. B. S. Haldane',
    difficulty: 5,
    reward: 2000,
    status: 'open',
    summary: '一堆非生命物质，是怎么变成第一个活细胞的？',
    kid: '几十亿年前，地球只是一团岩石和海洋。但不知怎么，里面冒出了能自我复制的小东西——第一个"生命"。这是怎么发生的？科学家们还在争论。',
    formal: '在合理的原始地球条件下，复现或严格模拟从非生物化学到自复制系统的过程。',
    whyHard: '跨越化学、信息、代谢、空间组织多个层面。',
    aiPrompt: '介绍 RNA World、代谢优先、原始细胞假说、最新实验进展。',
    tags: ['生物化学', '自组织', '前生命']
  },
  {
    id: 'nitrogen-fixation',
    category: 'chemistry',
    title: '常温常压固氮',
    titleEn: 'Nitrogen Fixation at Ambient Conditions',
    year: 1960,
    proposer: '—',
    difficulty: 4,
    reward: 1500,
    status: 'open',
    summary: '空气里 78% 是氮气，能不能像豆科植物那样便宜地"吃"掉它做肥料？',
    kid: '空气中大部分是氮气，但植物和动物都不能直接用。工业上用 Haber-Bosch 法把氮气变成氨（化肥原料），要 400°C 高温、200 倍大气压，每年烧掉 1-2% 的全球能源。豆科植物靠根瘤菌常温常压搞定。我们能不能学会？',
    formal: '找到一种在常温常压下高效催化 N₂ → NH₃ 的催化剂或机制。',
    whyHard: 'N≡N 三键极强（945 kJ/mol），动力学障碍巨大。',
    aiPrompt: '解释 Haber-Bosch、生物固氮机理、均相催化研究。',
    tags: ['催化', '氨', '能源']
  },
  {
    id: 'carbon-capture',
    category: 'chemistry',
    title: '高效碳捕集',
    titleEn: 'Efficient Carbon Capture',
    year: 1990,
    proposer: '—',
    difficulty: 4,
    reward: 1500,
    status: 'open',
    summary: '如何便宜地把大气中的二氧化碳抓回来？',
    kid: '人类每年往大气里排 400 亿吨 CO₂。能不能在排放点和大气中都把它们抓回来？目前的办法要花很多钱（每吨 100-1000 美元），我们需要便宜 10-100 倍的办法。',
    formal: '开发能量需求 < 1 GJ/吨 CO₂ 捕集的材料或工艺，并具备工业级稳定性。',
    whyHard: 'CO₂ 浓度低（420 ppm），需要巨大通量；再生能耗高。',
    aiPrompt: '介绍 MOF、胺基溶剂、钙循环、直接空气捕集。',
    tags: ['气候', '材料', '能源']
  },
  {
    id: 'protein-design',
    category: 'chemistry',
    title: '从头设计蛋白质',
    titleEn: 'De Novo Protein Design',
    year: 2003,
    proposer: '—',
    difficulty: 4,
    reward: 1500,
    status: 'partially_solved',
    summary: '让 AI 像设计房子一样，按需设计出能做特定工作的新蛋白质。',
    kid: '蛋白质是身体里的"小机器"，每种蛋白质有不同形状做不同事（比如消化食物、对抗病毒）。能不能让电脑帮我们设计"全新"的蛋白质，做我们想要的事？AlphaFold 和 David Baker 的工作让这变可能了，但还有很长的路。',
    formal: '为任意指定的功能（结合、催化、结构），可靠地设计稳定、可溶、可表达的蛋白质。',
    whyHard: '序列-结构-功能映射复杂，湿实验验证昂贵。',
    aiPrompt: '介绍 RFdiffusion、ProteinMPNN、最新 de novo 蛋白设计突破。',
    tags: ['蛋白设计', 'AI', '合成生物']
  },

  // ========== 生命科学 ==========
  {
    id: 'consciousness',
    category: 'philosophy',
    title: '意识的"难问题"',
    titleEn: 'Hard Problem of Consciousness',
    year: 1995,
    proposer: 'David Chalmers',
    difficulty: 5,
    reward: 3000,
    status: 'open',
    summary: '为什么物理过程会产生"体验"（比如疼痛的红、咖啡的香）？',
    kid: '你看到红色、闻到咖啡香、感到疼痛——这些"主观感受"是怎么从一堆原子和电信号里冒出来的？为什么不是像机器人一样"处理信息"而没有"感觉"？哲学家 David Chalmers 把这叫"难问题"。',
    formal: '解释为什么物理过程伴随现象体验（qualia），并提出可检验的理论（IIT、GWT、PP 等等）。',
    whyHard: '从客观（脑活动）到主观（体验）的鸿沟，目前没有共识理论。',
    aiPrompt: '介绍意识难问题、Chalmers、Dennett、IIT、全局工作空间、整合信息论。',
    tags: ['意识', 'qualia', '哲学']
  },
  {
    id: 'aging',
    category: 'biology',
    title: '衰老机制与逆转',
    titleEn: 'Biology of Aging',
    year: 1990,
    proposer: '—',
    difficulty: 4,
    reward: 2000,
    status: 'partially_solved',
    summary: '我们为什么会变老？能不能让人类显著延寿？',
    kid: '人为什么会变老？为什么小鼠只能活 2 年，乌龟能活 200 年？现代生物学发现了一些"衰老标志"（端粒、衰老细胞、线粒体……）。能不能通过干预这些机制让人类活得更久更健康？',
    formal: '识别驱动哺乳动物衰老的核心可干预机制，并通过临床干预显著延长人类健康寿命。',
    whyHard: '衰老是多因素过程，机制之间相互纠缠。',
    aiPrompt: '介绍 9 个衰老标志、Senolytics、Yamanaka 因子、雷帕霉素。',
    tags: ['衰老', '端粒', '长寿']
  },
  {
    id: 'cancer-cure',
    category: 'biology',
    title: '癌症的通用治愈',
    titleEn: 'Universal Cure for Cancer',
    year: 1971,
    proposer: '—',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '癌症其实是几百种不同的病。能不能找到对所有癌症都有效的统一办法？',
    kid: '"癌症"其实是 200 多种病的统称，每种都不一样。有的长在肺，有的长在骨头。我们能不能找到一种方法对付所有癌症？现在有免疫疗法（让免疫系统攻击癌症）这种通用思路的雏形。',
    formal: '找到一种对所有癌种都安全有效的统一治疗机制（候选：通用 CAR-T、癌疫苗、计算免疫学）。',
    whyHard: '癌症和正常细胞太像，免疫系统难以分辨。',
    aiPrompt: '介绍癌症的异质性、CAR-T、PD-1/PD-L1、个性化新抗原疫苗。',
    tags: ['癌症', '免疫疗法', 'CAR-T']
  },
  {
    id: 'alzheimer',
    category: 'biology',
    title: '阿尔茨海默病机制',
    titleEn: "Alzheimer's Disease Mechanism",
    year: 1906,
    proposer: 'A. Alzheimer',
    difficulty: 4,
    reward: 2000,
    status: 'open',
    summary: '为什么老年人的记忆会被偷走？我们能阻止吗？',
    kid: '很多爷爷奶奶记不住事情，会迷路、忘记亲人名字。这种病叫阿尔茨海默病（俗称老年痴呆）。科学家发现大脑里有些"垃圾蛋白"堆积，但到底是垃圾导致疾病，还是疾病产生垃圾？还吵不清。',
    formal: '阐明 AD 的因果链（Aβ vs Tau vs 神经炎症 vs 代谢），并基于此开发疾病修饰疗法（DMT）。',
    whyHard: '致病假说 30+ 种，临床试验失败率 99%。',
    aiPrompt: '介绍 amyloid 假说、Tau 假说、神经炎症、gliosis、Lecanemab 等。',
    tags: ['神经退行', 'Aβ', 'Tau']
  },
  {
    id: 'whole-brain-emulation',
    category: 'biology',
    title: '全脑模拟',
    titleEn: 'Whole Brain Emulation',
    year: 2008,
    proposer: '—',
    difficulty: 5,
    reward: 3000,
    status: 'partially_solved',
    summary: '把一个真实大脑完整地"拷贝"到计算机里。',
    kid: '如果能扫描一个真实大脑的每一个连接和分子，然后在电脑里"重新播放"，我们就能在计算机上运行一个数字版的"人"。听起来像科幻，但前沿神经科学正在朝这个方向走。',
    formal: '扫描并建模一个完整生物大脑的连通性和动力学，并在硬件上实现功能等价。',
    whyHard: '人脑有 ~860 亿神经元、~100 万亿突触，需要 PB 级扫描和建模。',
    aiPrompt: '介绍 connectomics、果蝇/线虫全脑连接组、AI 神经模拟。',
    tags: ['神经科学', '连接组', '意识']
  },
  {
    id: 'antibiotic-resistance',
    category: 'biology',
    title: '抗生素耐药性',
    titleEn: 'Antibiotic Resistance',
    year: 1940,
    proposer: '—',
    difficulty: 4,
    reward: 2000,
    status: 'open',
    summary: '细菌越来越不怕药了。我们能不能找到新办法？',
    kid: '过去 100 年我们靠抗生素打败了很多感染。但细菌会"学习"，一代代进化出耐药性。WHO 说，到 2050 年耐药菌每年可能杀死 1000 万人，超过癌症。我们需要新一代武器。',
    formal: '发现或合成能克服现有耐药机制的新型抗菌机制（候选：噬菌体、抗菌肽、AI 设计新药）。',
    whyHard: '细菌进化很快；新药开发周期长、回报低。',
    aiPrompt: '介绍抗生素耐药机制、新抗生素开发管线、AI 辅助药物发现。',
    tags: ['耐药', '抗生素', '公共卫生']
  },
  {
    id: 'cell-reprogramming',
    category: 'biology',
    title: '细胞重编程',
    titleEn: 'Cell Reprogramming',
    year: 2006,
    proposer: 'S. Yamanaka',
    difficulty: 4,
    reward: 1500,
    status: 'partially_solved',
    summary: '把一种细胞"变"成另一种，比如把皮肤细胞变成神经元。',
    kid: '你身上的皮肤细胞、心脏细胞、神经细胞都来自同一个受精卵，但后来变得不一样。Yamanaka 发现只要开几个"开关"（Yamanaka 因子），就能把皮肤细胞变回"小婴儿"状态，再变能任何细胞。这给再生医学打开了一扇门。',
    formal: '精确、可控地将体内任何成体细胞重编程为任何目标细胞类型，无肿瘤风险。',
    whyHard: '效率低、有肿瘤风险、表观遗传记忆问题。',
    aiPrompt: '介绍 Yamanaka 因子、部分重编程、体内重编程的最新进展。',
    tags: ['再生医学', 'iPSC', '表观遗传']
  },

  // ========== 计算机 ==========
  {
    id: 'agi',
    category: 'cs',
    title: '通用人工智能 (AGI)',
    titleEn: 'Artificial General Intelligence',
    year: 1956,
    proposer: '—',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '造出像人一样能思考、解决任何智力任务的 AI。',
    kid: '现在的 AI 都很"专"：下棋的 AI 不能开车，写文章的 AI 不能画画。AGI 想要一个 AI 像人一样，什么都能学、什么都能想。这件事能不能做到、什么时候做到，没人知道。',
    formal: '构造一个能跨领域、跨任务达到或超过人类水平智能的系统。',
    whyHard: '缺乏对"通用智能"的形式化定义；现有 scaling 是否有极限未知。',
    aiPrompt: '介绍 AGI 定义争论、scaling 假设、SAM、AIXI 框架。',
    tags: ['AGI', 'AI 安全', '智能']
  },
  {
    id: 'alignment',
    category: 'cs',
    title: 'AI 对齐',
    titleEn: 'AI Alignment',
    year: 2000,
    proposer: '—',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '怎么让比人还聪明的 AI 真的按人的意思做？',
    kid: '如果你有一只能听懂"做事"的魔法精灵，你怎么确保它做的事真的是你想的？比如你说"给我倒杯水"，它可能把家里所有水都倒完。AI 比精灵更危险——因为它可能比你还聪明。',
    formal: '对能力超过人类的 AI 系统，构造出可证明或可验证的、对齐训练与运行时监控机制。',
    whyHard: 'AI 目标难以形式化；自我修改系统的目标稳定性问题。',
    aiPrompt: '介绍 alignment 核心问题、outer/inner alignment、RLHF、debate、scalable oversight。',
    tags: ['AI 安全', '对齐', 'scalable oversight']
  },
  {
    id: 'software-verification',
    category: 'cs',
    title: '可扩展的软件验证',
    titleEn: 'Scalable Software Verification',
    year: 1970,
    proposer: '—',
    difficulty: 4,
    reward: 1500,
    status: 'open',
    summary: '自动证明大型软件没有 bug。',
    kid: '手机上的 app、医院里的核磁共振机、银行系统——都有 bug 风险。能不能让电脑"读"一段代码，告诉你"这段代码绝对没 bug"？现在只能验证非常小的程序，对真实软件完全不行。',
    formal: '为工业级软件构造全自动、形式化、可扩展的程序验证流水线。',
    whyHard: '状态空间爆炸；规范难以完整；工具链不完善。',
    aiPrompt: '介绍 model checking、Coq/Lean 在工业代码的应用、LLM 辅助验证。',
    tags: ['形式化', '验证', '静态分析']
  },
  {
    id: 'homomorphic-encryption',
    category: 'cs',
    title: '全同态加密实用化',
    titleEn: 'Practical Fully Homomorphic Encryption',
    year: 2009,
    proposer: 'C. Gentry',
    difficulty: 4,
    reward: 1500,
    status: 'partially_solved',
    summary: '让电脑在"看不到内容"的情况下也能处理你的数据。',
    kid: '你想让医院 AI 帮你看病，但不想把病历给 AI。同态加密可以让你"加密"的病历送到 AI，AI 直接在"乱码"上计算，把结果给你，你解密后看到诊断。AI 看不到你的隐私。',
    formal: '构造一种 FHE 方案，运算速度达到非加密执行的 10× 以内，且支持任意深度电路。',
    whyHard: 'bootstrapping 开销巨大；噪声管理复杂。',
    aiPrompt: '介绍 FHE 原理（BFV/CKKS/BGV）、bootstracking、硬件加速。',
    tags: ['加密', '隐私', '计算']
  },
  {
    id: 'quantum-internet',
    category: 'engineering',
    title: '量子互联网',
    titleEn: 'Quantum Internet',
    year: 2000,
    proposer: '—',
    difficulty: 4,
    reward: 2000,
    status: 'open',
    summary: '让量子计算机像现在的电脑一样互联互通。',
    kid: '现在的网络发的是经典比特（0 或 1）。量子互联网发的是"量子比特"——一种"既是0又是1"的神奇状态。它能做不能被偷听的安全通信，连远程量子计算机一起工作。',
    formal: '建立全球规模的量子互联网，支持量子纠缠分发、端到端量子隐形传态、量子中继。',
    whyHard: '光子损耗严重；需要量子中继和量子存储器。',
    aiPrompt: '介绍量子中继、量子隐形传态、墨子号进展。',
    tags: ['量子', '网络', '通信']
  },
  {
    id: 'translation-parity',
    category: 'cs',
    title: '通用机器翻译达到人类水平',
    titleEn: 'Human-Level Machine Translation',
    year: 1950,
    proposer: '—',
    difficulty: 3,
    reward: 1000,
    status: 'partially_solved',
    summary: '让任意两种语言之间的翻译都能达到专业人类译员水平。',
    kid: '现在 Google 翻译已经能做基本翻译了，但在俚语、专业内容、文化背景上还是不行。如果 AI 能像专业翻译家一样工作，世界会变得更小。',
    formal: '在所有语言对、所有领域、所有语域上达到人类专业译员水平。',
    whyHard: '文化、上下文、隐喻、风格难处理。',
    aiPrompt: '介绍 NMT、LLM 翻译、长上下文、文化迁移。',
    tags: ['NLP', '翻译', 'LLM']
  },

  // ========== 哲学 ==========
  {
    id: 'free-will',
    category: 'philosophy',
    title: '自由意志',
    titleEn: 'Free Will',
    year: -350,
    proposer: 'Aristotle',
    difficulty: 5,
    reward: 2000,
    status: 'open',
    summary: '你的选择真的是"你"做的吗？还是被物理定律预先决定的？',
    kid: '你以为是"你"决定吃冰淇淋还是苹果。但每个神经元的放电都遵循物理定律。如果宇宙的初始状态定好了，所有未来就定好了。这是决定论。那"你"在做什么？',
    formal: '自由意志是否能与物理决定论/非决定论兼容？构造一个相容论或自由论的形式框架。',
    whyHard: '概念模糊；实验难以进行。',
    aiPrompt: '介绍 compatibilism、libertarianism、determinism、neuroscience 实验。',
    tags: ['自由', '决定论', '形而上学']
  },
  {
    id: 'meaning-of-life',
    category: 'philosophy',
    title: '生命的意义',
    titleEn: 'Meaning of Life',
    year: -400,
    proposer: 'Plato',
    difficulty: 5,
    reward: 2000,
    status: 'open',
    summary: '如果宇宙不在乎我们，我们怎么能活得有意义？',
    kid: '宇宙在不在意我们呢？大概不在意。但我们能不能自己"造"出意义？很多大哲学家（孔子、佛陀、萨特、维特根斯坦）都想过这个问题。',
    formal: '是否存在客观的、可形式化的生命意义判定标准？',
    whyHard: '主观 vs 客观，meta-ethics 之争。',
    aiPrompt: '介绍存在主义、佛教、儒家、荒诞主义、Terror Management Theory。',
    tags: ['意义', '存在主义', '幸福']
  },
  {
    id: 'moral-objectivity',
    category: 'philosophy',
    title: '道德的客观性',
    titleEn: 'Moral Objectivity',
    year: -380,
    proposer: 'Plato',
    difficulty: 5,
    reward: 2000,
    status: 'open',
    summary: '对错到底是不是真的？还是只是我们觉得？',
    kid: '你说"杀人是错的"。但凭什么？这是真实的"事实"，还是人类的"约定"？哲学家们吵了 2500 年。',
    formal: '道德真理是否有客观基础？建构可形式化、可证伪的元伦理学框架。',
    whyHard: 'meta-ethics 之争，概念分歧大。',
    aiPrompt: '介绍 moral realism、anti-realism、constructivism、moral semantics。',
    tags: ['伦理', 'meta-ethics', '真']
  },

  // ========== 工程 ==========
  {
    id: 'fusion',
    category: 'engineering',
    title: '可控核聚变',
    titleEn: 'Controlled Fusion',
    year: 1950,
    proposer: '—',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '在地球上像太阳一样"烧"出无限清洁能源。',
    kid: '太阳靠"烧"氢气变成氦气来发光发热，叫核聚变。地球上能不能也这样做？如果能，能源就几乎无限了。问题是：太阳能靠巨大引力压住核聚变，地球没有。',
    formal: '实现 Q>10 的稳定可控聚变（能量增益），并维持 net-positive electricity。',
    whyHard: '1 亿度等离子体约束、氚自持、材料损伤。',
    aiPrompt: '介绍 tokamak、stellarator、ICF、SPARC/ITER、NIF 进展。',
    tags: ['能源', '聚变', '等离子体']
  },
  {
    id: 'space-elevator',
    category: 'engineering',
    title: '太空电梯',
    titleEn: 'Space Elevator',
    year: 1895,
    proposer: 'K. Tsiolkovsky',
    difficulty: 5,
    reward: 3000,
    status: 'open',
    summary: '造一条 36000 公里长的"电梯"通向太空。',
    kid: '火箭运东西上太空要花很多钱（一公斤几十万美元）。能不能造一条长长的"电梯"从地球一直伸到太空，东西坐电梯上去？听着科幻，但材料学上没有根本不可能。问题是要找到能撑住自身重量的材料。',
    formal: '开发强度 / 密度比 > 4 × 10⁷ Nm/kg 的材料，并完成 36000 km 缆绳的设计、制造、部署。',
    whyHard: '碳纳米管量产未实现；动力学问题。',
    aiPrompt: '介绍碳纳米管、Graphene、动力学、Anchor、天钩 vs 地基方案。',
    tags: ['航天', '材料', '基础设施']
  },
  {
    id: 'desalination',
    category: 'engineering',
    title: '廉价海水淡化',
    titleEn: 'Cheap Desalination',
    year: 1950,
    proposer: '—',
    difficulty: 3,
    reward: 1500,
    status: 'open',
    summary: '把海水变成能喝的水，足够便宜、足够多。',
    kid: '地球 71% 是水，但 97% 是咸的不能喝。20 亿人缺干净水。能不能把海水变成饮用水，便宜到大家都用得起？现在能淡化海水，但每吨要 1-3 美元。',
    formal: '实现能耗 < 1 kWh/m³ 海水淡化，并能处理高盐度 / 多污染水源。',
    whyHard: '膜污染、能耗、生物污染。',
    aiPrompt: '介绍反渗透、电容去离子、仿生膜、正渗透。',
    tags: ['水', '能源', '膜']
  },
  {
    id: 'reusable-rocket',
    category: 'engineering',
    title: '完全可重复使用火箭',
    titleEn: 'Fully Reusable Rockets',
    year: 2010,
    proposer: '—',
    difficulty: 3,
    reward: 2000,
    status: 'partially_solved',
    summary: '让火箭像飞机一样能多次使用，把上太空的成本降到 1/100。',
    kid: '火箭现在每用一次就扔掉（像纸飞机）。SpaceX 已经在回收部分火箭了。如果整支火箭（连上面级）都能完全重复使用，进太空的成本会大幅降低。',
    formal: '实现轨道级完全可重复使用运载系统，单次入轨成本 < $100/kg。',
    whyHard: '再入气动加热、翻新成本、轨道级上面级回收。',
    aiPrompt: '介绍 SpaceX Starship、Blue Origin、Tank 翻转、单入轨成本趋势。',
    tags: ['航天', '可重复', '成本']
  },
  {
    id: 'bci',
    category: 'engineering',
    title: '高带宽脑机接口',
    titleEn: 'High-Bandwidth Brain-Computer Interface',
    year: 2010,
    proposer: '—',
    difficulty: 4,
    reward: 2000,
    status: 'partially_solved',
    summary: '让大脑和电脑直接"对话"，带宽达到自然语言级别。',
    kid: '你脑子里想的事能不能直接传到电脑？现在 Neuralink 等公司可以让你"用脑子打字"，但很慢。能不能达到"想到什么，电脑就打出什么"的速度？',
    formal: '实现 > 1 Mbps、单神经元分辨率、双向、长期稳定的脑机接口。',
    whyHard: '电极排异、信号解码、伦理。',
    aiPrompt: '介绍 Neuralink、Utah Array、ECoG、fMRI、光遗传。',
    tags: ['BCI', '神经', '接口']
  },
  {
    id: 'cheap-solar-fuel',
    category: 'engineering',
    title: '廉价人工光合作用',
    titleEn: 'Artificial Photosynthesis',
    year: 1972,
    proposer: 'Fujishima / Honda',
    difficulty: 5,
    reward: 2500,
    status: 'open',
    summary: '像植物一样直接用阳光把水和二氧化碳变成燃料。',
    kid: '植物能用阳光、水和二氧化碳做糖（燃料）。我们能不能造一个"人造叶子"，用阳光直接把水变成氢气（清洁燃料）？这能让太阳能变成可储存的燃料。',
    formal: '实现 STH（solar-to-hydrogen）效率 > 10%、寿命 > 1000 小时的人工光合器件。',
    whyHard: '需要同时高效吸收光、催化水分解、稳定。',
    aiPrompt: '介绍光催化、电催化、Z-scheme、biomimetic leaf。',
    tags: ['能源', '催化', '光']
  },

  // ========== 社会 ==========
  {
    id: 'poverty',
    category: 'social',
    title: '消除极端贫困',
    titleEn: 'Ending Extreme Poverty',
    year: 1990,
    proposer: 'UN',
    difficulty: 5,
    reward: 3000,
    status: 'partially_solved',
    summary: '让全世界 7 亿每天靠不到 2 美元生活的人能体面生活。',
    kid: '世界上还有 7 亿小朋友每天吃不饱饭、没学上、没干净水。30 年来极端贫困比例从 36% 降到 9%，但要彻底消除需要新办法。',
    formal: '把全球极端贫困率（< $2.15/天）从 9% 降到 < 1%，并可持续。',
    whyHard: '政治、制度、地理、健康多重交织。',
    aiPrompt: '介绍 GiveDirectly、conditional cash transfer、microfinance、effective altruism。',
    tags: ['贫困', '发展', '援助']
  },
  {
    id: 'misinformation',
    category: 'social',
    title: '虚假信息治理',
    titleEn: 'Combating Misinformation',
    year: 2010,
    proposer: '—',
    difficulty: 4,
    reward: 1500,
    status: 'open',
    summary: '让真相跑赢谎言。',
    kid: '网上谣言、假新闻、深度伪造……人们越来越分不清真假。怎么在不变成"控制思想"的情况下，让大家更容易看到真相？',
    formal: '建立可大规模部署、能保护言论自由且显著降低虚假信息传播的治理框架。',
    whyHard: '经济激励（点击量）、政治利用、AI 生成内容。',
    aiPrompt: '介绍深度伪造检测、事实核查、平台治理、reductio。',
    tags: ['信息', '治理', 'AI']
  },
  {
    id: 'sustainable-energy',
    category: 'social',
    title: '全球可持续能源',
    titleEn: 'Global Sustainable Energy',
    year: 2015,
    proposer: 'UN',
    difficulty: 5,
    reward: 3000,
    status: 'open',
    summary: '让全世界都用到便宜、清洁、不会用完的能源。',
    kid: '化石能源（煤、石油、天然气）让人类进步，但也让气候变坏。能不能让全世界 80 亿人都用上太阳能、风能、核能？需要在技术、政策、基础设施上同时发力。',
    formal: '实现全球能源系统的去碳化（< 1.5°C 路径），且人人可负担。',
    whyHard: '电网、储能、土地、政治。',
    aiPrompt: '介绍 IRENA、IEA 路径、储能、电网、Just Transition。',
    tags: ['能源', '气候', '公正转型']
  },
  {
    id: 'education-reform',
    category: 'social',
    title: '教育规模化个性化',
    titleEn: 'Personalized Education at Scale',
    year: 2000,
    proposer: '—',
    difficulty: 4,
    reward: 2000,
    status: 'open',
    summary: '让每个孩子都能得到"一对一家教"级别的教育。',
    kid: '好的家教能根据你的特点调整教学，但好家教贵、不能普及。如果 AI 老师能理解每个孩子的水平、兴趣、状态，规模化提供一对一教育？',
    formal: '构造可大规模部署的个性化学习系统，使学习效果显著超过传统课堂平均水平。',
    whyHard: '动机、社会互动、评估、教师角色。',
    aiPrompt: '介绍 Khanmigo、Duolingo Max、个性化推荐、学习分析。',
    tags: ['教育', 'AI', '个性化']
  },
  {
    id: 'polarization',
    category: 'social',
    title: '政治极化',
    titleEn: 'Political Polarization',
    year: 2010,
    proposer: '—',
    difficulty: 4,
    reward: 2000,
    status: 'open',
    summary: '为什么社会越来越分裂？怎么让人重新能好好说话？',
    kid: '你可能听过爸爸妈妈因为政治观点吵架。世界上很多国家都越来越"左 vs 右"，大家越来越不愿意听对方说话。怎么让社会重新能好好讨论？',
    formal: '理解、预测和缓解政治极化的可干预机制，跨越媒体、制度、文化层面。',
    whyHard: '激励机制（关注度）、身份政治、媒体算法。',
    aiPrompt: '介绍 echo chamber、sorting、桥接对话、deliberative democracy。',
    tags: ['政治', '社会', '对话']
  },
  {
    id: 'longevity-equity',
    category: 'social',
    title: '寿命延长的公平性',
    titleEn: 'Equity in Longevity Extension',
    year: 2030,
    proposer: '—',
    difficulty: 4,
    reward: 1500,
    status: 'open',
    summary: '如果人类能活 150 岁，谁有资格、谁付钱？',
    kid: '如果有一天医学能让人活 150 岁，谁先用？富人和穷人之间的寿命差会不会变得更大？我们需要在技术成熟前就设计好制度。',
    formal: '为长寿增强技术提出一个全球公平分配框架，避免寿命鸿沟加剧不平等。',
    whyHard: '未知技术、多元价值观、地缘政治。',
    aiPrompt: '介绍 longevity dividend、access、equity、伦理。',
    tags: ['长寿', '公平', '伦理']
  },

  // ========== 数学 (新增经典) ==========
  {
    id: 'four-color',
    category: 'mathematics',
    title: '四色定理的简单证明',
    titleEn: 'A Simple Proof of the Four Color Theorem',
    year: 1852,
    proposer: 'F. Guthrie',
    difficulty: 3,
    reward: 500,
    status: 'solved',
    summary: '任何地图都能用 4 种颜色涂，使相邻国家颜色不同——但证明需要 1000+ 行计算机验证。',
    kid: '画一张地图，用 4 种颜色让相邻的国家颜色都不同。听起来简单，但 1852 年提出后 124 年才被严格证明，而且必须用电脑算！',
    formal: '为任意平面图的四色染色给出不依赖计算机的、人类可读的证明。',
    whyHard: '现有证明（Appel-Haken 1976）依赖大量案例枚举，几乎无法被人审查。',
    aiPrompt: '解释四色定理的历史、Appel-Haken 证明、计算机辅助证明的争议。',
    tags: ['图论', '拓扑', '经典']
  },
  {
    id: 'langlands',
    category: 'mathematics',
    title: '朗兰兹纲领',
    titleEn: 'Langlands Program',
    year: 1967,
    proposer: 'Robert Langlands',
    difficulty: 5,
    reward: 3000,
    status: 'partially_solved',
    summary: '把数论、几何、分析、表示论编织成一张大网。',
    kid: '有一张大网，把数学里看起来不相关的领域（数论、几何、群论）都连起来。这张网就是朗兰兹纲领。如果能完全织好，整本数学书都能换一种写法。',
    formal: '证明函数域情形的朗兰兹对应（包括 endoscopic 和 trace formula 实现）。',
    whyHard: '横跨多个数学分支，需要"百科全书式"的工作。',
    aiPrompt: '介绍 Langlands Program、Arthur-Selberg trace formula、几何朗兰兹。',
    tags: ['数论', '表示论', '大统一']
  },

  // ========== 物理 (新增热点) ==========
  {
    id: 'swampland',
    category: 'physics',
    title: 'Swampland 猜想',
    titleEn: 'Swampland Conjectures',
    year: 2006,
    proposer: 'C. Vafa 等',
    difficulty: 5,
    reward: 2000,
    status: 'open',
    summary: '什么样的低能物理理论能从一个自洽的量子引力理论中涌现？',
    kid: '宇宙像一片"景观"(landscape)，允许的低能物理理论就是陆地；"swampland"是看起来能存在但实际不行的沼泽。我们想精确划出"陆地"的边界。',
    formal: '为有效场论能被嵌入到弦理论/量子引力给出必要条件。',
    whyHard: '涉及弦理论的全部复杂性；许多猜想还没有严格表述。',
    aiPrompt: '介绍 swampland 距离猜想、de Sitter conjecture、refined de Sitter。',
    tags: ['弦论', '量子引力', '现象学']
  },
  {
    id: 'black-hole-info',
    category: 'physics',
    title: '黑洞信息悖论',
    titleEn: 'Black Hole Information Paradox',
    year: 1976,
    proposer: 'J. Preskill / S. Hawking',
    difficulty: 5,
    reward: 2000,
    status: 'partially_solved',
    summary: '掉进黑洞的信息到底去哪了？',
    kid: '你扔一本字典进黑洞，按霍金辐射它会蒸发。但量子力学说信息不能消失。这两个打架！',
    formal: '在量子引力框架下，严格证明掉入黑洞的信息能在霍金辐射中被恢复（Page curve 的微观推导）。',
    whyHard: '需要量子引力；近年 Island 公式有进展但还没完全解决问题。',
    aiPrompt: '介绍 firewall paradox、ER=EPR、island formula、Page curve。',
    tags: ['黑洞', '量子引力', '信息']
  },

  // ========== 化学 (新增) ==========
  {
    id: 'molecular-machine',
    category: 'chemistry',
    title: '可编程分子机器',
    titleEn: 'Programmable Molecular Machines',
    year: 1982,
    proposer: 'K. Eric Drexler',
    difficulty: 4,
    reward: 1500,
    status: 'partially_solved',
    summary: '造出能在分子尺度上完成特定任务的"机器"。',
    kid: '如果你能造出和分子一样小的机器人，让它在你血管里跑来跑去治病，会怎样？DNA 折纸、分子马达已经是雏形。',
    formal: '实现完全可编程、可寻址、可重复编程的分子级机器。',
    whyHard: '需要原子精度控制；化学合成极限。',
    aiPrompt: '介绍 DNA 折纸、分子马达、纳米医学、原子精度制造。',
    tags: ['纳米', '分子', 'DNA']
  },

  // ========== 生物 (新增) ==========
  {
    id: 'memory-erasure',
    category: 'biology',
    title: '选择性记忆删除',
    titleEn: 'Selective Memory Erasure',
    year: 2010,
    proposer: '—',
    difficulty: 4,
    reward: 2000,
    status: 'partially_solved',
    summary: '能不能精确删除某一段创伤记忆而不影响其他记忆？',
    kid: '如果一个人经历过很可怕的事，记一辈子很痛苦。能不能用医学方法只把"可怕"的记忆擦掉，别的都留下？科学家在小鼠上已经做出来了。',
    formal: '在人体内实现特定记忆痕迹的精确擦除，不影响其他神经活动。',
    whyHard: '记忆是分布式的；伦理问题严重。',
    aiPrompt: '介绍记忆固化、reconsolidation、propranolol、基因治疗在动物模型中的实验。',
    tags: ['神经', 'PTSD', '伦理']
  },
  {
    id: 'de-extinction',
    category: 'biology',
    title: '已灭绝物种复活',
    titleEn: 'De-Extinction',
    year: 2003,
    proposer: '—',
    difficulty: 4,
    reward: 1500,
    status: 'partially_solved',
    summary: '把已经灭绝的动物（猛犸象、渡渡鸟）带回来。',
    kid: '恐龙复活还太难，但猛犸象、袋狼这些灭绝没很久的动物呢？科学家正尝试用它们的近亲+基因编辑复活。',
    formal: '基于现存近亲物种和 CRISPR 基因编辑，复原已灭绝物种的功能性基因组。',
    whyHard: '遗传多样性低；伦理和生态争议大。',
    aiPrompt: '介绍 Colossal Biosciences、猛犸象计划、渡渡鸟计划、伦理。',
    tags: ['CRISPR', '保护', '伦理']
  },

  // ========== 计算机 (新增) ==========
  {
    id: 'leakage-resilient-crypto',
    category: 'cs',
    title: '抗侧信道的密码学',
    titleEn: 'Leakage-Resilient Cryptography',
    year: 2008,
    proposer: '—',
    difficulty: 4,
    reward: 1000,
    status: 'partially_solved',
    summary: '设计在有信息泄露的现实中仍然安全的密码学。',
    kid: '我们以为密码很安全，但黑客通过观察电脑的功耗、声音、电磁波也能偷到秘密。我们能造出不怕这种"偷看"的密码吗？',
    formal: '构造对任意有界信息泄露模型仍保持可证明安全的密码学原语。',
    whyHard: '需要新的数学工具；侧信道种类繁多。',
    aiPrompt: '介绍 side-channel attack、noisy leakage model、Leakage-Resilient PRF。',
    tags: ['密码学', '安全', '硬件']
  },
  {
    id: 'self-driving-l5',
    category: 'engineering',
    title: 'L5 级自动驾驶',
    titleEn: 'Level 5 Self-Driving',
    year: 2020,
    proposer: '—',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: '在任何天气、任何道路、任何情况下都能自动驾驶。',
    kid: '想象你坐上车，告诉它"回家"，它就真的安全把你带回家——不用你碰方向盘。L5 就是这个意思。现在所有自动驾驶都还需要人盯着。',
    formal: '在所有 ODD（设计运行域）下达到或超过人类驾驶员安全水平，且能处理长尾边缘案例。',
    whyHard: '感知、推理、伦理、立法多线作战。',
    aiPrompt: '介绍 Waymo、Tesla FSD、感知-预测-规划栈、长尾问题。',
    tags: ['AI', '交通', '工程']
  },

  // ========== 哲学 (新增) ==========
  {
    id: 'zombie-thought',
    category: 'philosophy',
    title: '哲学僵尸论证',
    titleEn: 'Philosophical Zombies',
    year: 1990,
    proposer: 'D. Chalmers',
    difficulty: 4,
    reward: 1000,
    status: 'open',
    summary: '一个完全像你但"没有内在体验"的人在物理上可能吗？',
    kid: '有没有一种"僵尸"——长得和你一模一样，会说话会笑会哭，但里面是空的，没有任何"感受"？如果可能，那意识就不是物理可以解释的。',
    formal: '形而上学地，p-zombie 是否在概念上自洽？',
    whyHard: '依赖于意识的形而上学。',
    aiPrompt: '介绍 p-zombie、Chalmers、consciousness in physicalism。',
    tags: ['意识', '心物', '形而上学']
  },
  {
    id: 'simulation-arg',
    category: 'philosophy',
    title: '我们活在模拟中吗？',
    titleEn: 'Simulation Argument',
    year: 2003,
    proposer: 'N. Bostrom',
    difficulty: 4,
    reward: 1000,
    status: 'open',
    summary: '如果未来能模拟意识，那我们很可能就活在模拟中。',
    kid: '玩过电子游戏吗？游戏里的角色不知道自己是"游戏里的"。如果未来人类能做出包含意识的模拟，那我们很可能就是"被模拟出来的"。',
    formal: 'Bostrom 三难推理的哪一支为真？给出可证伪的判别条件。',
    whyHard: '无法设计实验直接证伪。',
    aiPrompt: '介绍 Bostrom trilemma、Nick Bostrom 2019 论文、Elon Musk 的看法。',
    tags: ['模拟', '意识', '形而上学']
  },

  // ========== 工程 (新增) ==========
  {
    id: 'mr-safe-mri',
    category: 'engineering',
    title: '便携式全身 MRI',
    titleEn: 'Portable Whole-Body MRI',
    year: 2020,
    proposer: '—',
    difficulty: 4,
    reward: 2000,
    status: 'partially_solved',
    summary: '把 MRI 设备做到便携、低成本、无需氦。',
    kid: '现在医院里的 MRI 又大又贵（一台几百万美元），还要用稀有的氦气。能不能做出便宜、轻便的版本，让基层医院甚至救护车都能用？',
    formal: '实现 0.5T 以上场强、< 500kg 重量、< $50k 成本的全身 MRI 系统。',
    whyHard: '磁场均匀性、低温超导。',
    aiPrompt: '介绍 Hyperfine、portable MRI、低场 MRI、深度学习重建。',
    tags: ['医疗', '成像', '便携']
  },
  {
    id: 'hydrogen-storage',
    category: 'engineering',
    title: '常温常压储氢',
    titleEn: 'Hydrogen Storage at Ambient Conditions',
    year: 2020,
    proposer: '—',
    difficulty: 4,
    reward: 2500,
    status: 'open',
    summary: '把氢气像汽油一样安全便宜地存起来。',
    kid: '氢是清洁能源的明星，但很难存——要 700 倍大气压或者零下 253°C 液氢。能不能像加油一样方便地存？',
    formal: '实现 > 7% 重量密度、可逆循环 > 500 次、安全且廉价的常温常压储氢。',
    whyHard: '需要新型 MOF、化学氢化物或纳米材料。',
    aiPrompt: '介绍 MOF、LOHC、地下储氢、DOE 2025 目标。',
    tags: ['能源', '氢', '材料']
  },

  // ========== 社会 (新增) ==========
  {
    id: 'open-source-ai',
    category: 'cs',
    title: '开源通用 AI',
    titleEn: 'Open-Source AGI',
    year: 2024,
    proposer: '—',
    difficulty: 5,
    reward: 5000,
    status: 'open',
    summary: 'AGI 应该是开源的、所有人都能用吗？',
    kid: '如果有一天真的有"超级聪明"的 AI 了，它应该被几家大公司控制，还是所有人一起用？',
    formal: '构造一个安全、能力达到 AGI 水平、完全开源可验证的 AI 系统。',
    whyHard: '安全 vs 开放的权衡；治理问题。',
    aiPrompt: '介绍 OpenAI vs 开源、Llama、Mistral、DeepSeek、Alibaba Qwen。',
    tags: ['AI', '治理', '开源']
  },
  {
    id: 'longtermism',
    category: 'social',
    title: '长期主义决策',
    titleEn: 'Longtermist Decision-Making',
    year: 2017,
    proposer: 'W. MacAskill 等',
    difficulty: 4,
    reward: 1000,
    status: 'open',
    summary: '现在的决策如何考虑 1000 年后的人？',
    kid: '我们今天建一个核废料仓库，要确保它 10 万年安全。10 万年后的人会怎么看我们？这种"想得很远"的思考方式叫长期主义。',
    formal: '构造一个能在不确定未来下、可形式化的 longtermist 决策框架。',
    whyHard: '预测未来 1000 年几乎不可能；代际公平。',
    aiPrompt: '介绍 longtermism、MacAskill、effective altruism。',
    tags: ['伦理', '长期', '决策']
  }
];

// 派生：按类别分组
export const PROBLEMS_BY_CATEGORY = PROBLEMS.reduce((acc, p) => {
  (acc[p.category] = acc[p.category] || []).push(p);
  return acc;
}, {});

// 工具函数
export function getProblemById(id) {
  return PROBLEMS.find(p => p.id === id);
}

export function searchProblems(query) {
  if (!query) return PROBLEMS;
  const q = query.toLowerCase();
  return PROBLEMS.filter(p =>
    p.title.toLowerCase().includes(q) ||
    p.titleEn.toLowerCase().includes(q) ||
    p.summary.toLowerCase().includes(q) ||
    p.kid.toLowerCase().includes(q) ||
    p.tags.some(t => t.toLowerCase().includes(q))
  );
}
